{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pulse.pulse_sip_bridge",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "com.cloudwebrtc.webrtc",
          "module": "flutter_webrtc_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.github.dart_lang.jni",
          "module": "jni_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.github.dart_lang.jni_flutter",
          "module": "jni_flutter_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.pulse.pulse_sip_core",
          "module": "pulse_sip_core_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 20219861,
          "sha512": "da5635d75e034592851db4c224f6e551c9c75314d35622fc124243d027e4ee6d4b6e08ba9fbf60c0459bca5274125e1b5c86db9dbf5a32de19189f43caf1edd5",
          "sha256": "cdf86df73af2b2fd908b6404bc47eacb6faa848533bf6950755a559ec32c23aa",
          "sha1": "0da83285afded78ec6764a7fd4c1601cd43b23ee",
          "md5": "e9a709958197db72a05165c9631dd31a"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "com.cloudwebrtc.webrtc",
          "module": "flutter_webrtc_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.github.dart_lang.jni",
          "module": "jni_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.github.dart_lang.jni_flutter",
          "module": "jni_flutter_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.pulse.pulse_sip_core",
          "module": "pulse_sip_core_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 20219861,
          "sha512": "da5635d75e034592851db4c224f6e551c9c75314d35622fc124243d027e4ee6d4b6e08ba9fbf60c0459bca5274125e1b5c86db9dbf5a32de19189f43caf1edd5",
          "sha256": "cdf86df73af2b2fd908b6404bc47eacb6faa848533bf6950755a559ec32c23aa",
          "sha1": "0da83285afded78ec6764a7fd4c1601cd43b23ee",
          "md5": "e9a709958197db72a05165c9631dd31a"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_debug-1.0-sources.jar",
          "url": "flutter_debug-1.0-sources.jar",
          "size": 1227,
          "sha512": "84c1b57657726b4791764ac42c6eb6b15386170a94ded8858c358ff20c4616c4f010c4c87c1b81e89cab789147ac245ce76047fa0d6b67241d284636d5f9cb19",
          "sha256": "2a4d6cf03614cd23d34fd1f60470f2f209cd65597f113ec4e7b33ca8ad604b3c",
          "sha1": "cff24f5db5d7840375d86bba0461653438bc07eb",
          "md5": "8f2e8b97a0a7b8eefd7367daa394263a"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_debug-1.0-javadoc.jar",
          "url": "flutter_debug-1.0-javadoc.jar",
          "size": 261687,
          "sha512": "e1a6d33dda75d144f4e55191c618680bb96eaa38d844a6997ae3c2636b285645deb0b086688b72e6f364ace0729f67f8cc5e1f7299e04b1543dd49d0c30411a3",
          "sha256": "d9aa77c8f41815c9159984c3501460f6dfc6604ab5916a8ee4e35dee3c346d16",
          "sha1": "2166d022d582188b28e846f39b36a1082b5f9066",
          "md5": "7c80635e3e18a560f1391d955845529e"
        }
      ]
    }
  ]
}
