{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_profile-1.0.aar",
          "url": "shared_preferences_android_profile-1.0.aar",
          "size": 117754,
          "sha512": "4424c3b609a45938013a7f84ef0f7ca5307b77a9423058b4c81030cbf8ee66fb9d8eb63d94d35bc22eb6ad2cc20335475376d25cdff0c8e3950e487a86af93ec",
          "sha256": "d57e381f3e8965742664f1c47fcc2fd1fad9991f3ca477c0831f67029b6367ca",
          "sha1": "acbdb36dd6e6f2f4d50a563357a04898547cabfb",
          "md5": "f4ffa9320c6cfeff59695d5d556ec09c"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_profile-1.0.aar",
          "url": "shared_preferences_android_profile-1.0.aar",
          "size": 117754,
          "sha512": "4424c3b609a45938013a7f84ef0f7ca5307b77a9423058b4c81030cbf8ee66fb9d8eb63d94d35bc22eb6ad2cc20335475376d25cdff0c8e3950e487a86af93ec",
          "sha256": "d57e381f3e8965742664f1c47fcc2fd1fad9991f3ca477c0831f67029b6367ca",
          "sha1": "acbdb36dd6e6f2f4d50a563357a04898547cabfb",
          "md5": "f4ffa9320c6cfeff59695d5d556ec09c"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_profile-1.0-sources.jar",
          "url": "shared_preferences_android_profile-1.0-sources.jar",
          "size": 13712,
          "sha512": "2322077f316271d516b7a13c1a85aab6581228ea0e162c453224193ad43483785f75aff62fc6c4caf84db7bca653741e6c511789c8e80002dcbafdbe69b365a4",
          "sha256": "795cd668a3c81d21d93904f0d9577010f5d39a9a6a20b0c527bd78f1930961e7",
          "sha1": "aca57cb05a8d494b755f349cc32a2cfa18ea7165",
          "md5": "e01671777e4470c08cf818f20d90a1fd"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_profile-1.0-javadoc.jar",
          "url": "shared_preferences_android_profile-1.0-javadoc.jar",
          "size": 358833,
          "sha512": "7c003cd0412ed087989984c80690e212f10ad5a09addc0b22055fb65fec863a86cf9aad9af69d06969a5ba16b90a57a99e1e6af68a1443117d62f9f5ab642245",
          "sha256": "cbc7b5479ffa3be1e7f56f67ebe83312f8cf1fcefbcbe795c2e16acdecd9338b",
          "sha1": "b1898553123e3486a2b2b59c14bb8c8b4bf2d682",
          "md5": "9ffc0ed2d7d08d5617253f2a85c717d7"
        }
      ]
    }
  ]
}
